---
title: "Personal Projects"
author: "Marco Notaro"
date: last-modified
format:
  html:
    code-tools: false
---

## Developed software libraries

- [HEMDAG: a meta-learning tool for predicting novel biomedical associations from ontology data](https://hemdag.readthedocs.io/en/latest/)
- [obogaf-parser: a Perl module to parse biomedical ontology and gene association files](https://obogaf-parser.readthedocs.io/en/latest/)


## Contribution to open-source software libraries

- [Integration of nextflow pipelines in the FGCZ's cloud platform SUSHI (ATAC-Seq and CUT\&RUN)](https://github.com/uzh/ezRun/commits?author=marconotaro)
- [Development of a Ruby on Rails interface for CUT&RUN data analysis](https://github.com/uzh/sushi/commits?author=marconotaro)


## Genomics

- [Identification of breast cancer subtypes via a graph-based approach](cancer_subtypes/toc.qmd)


## Machine learning

- [Identifying biomarkers associated with weight loss using a Bayesian-optimized classifier](ml-nb/shap/biomarker_discovery_ornish.ipynb)
- [Predicting housing prices in California](ml-nb/classic/housing_prices.ipynb)
- [Predicting biomarker status imputing missing values](cancer_subtypes/r4_predict_erstatus.ipynb)
- [Predicting salary and new connections from network data](ml-nb/classic/ml_salary.ipynb)
- [Predicting viewer engagement with educational videos](ml-nb/classic/ml_video.ipynb)

## Deep learning

- [Predicting protein subcellular localization from aminoacid sequences with PyTorch](ml-nb/deeplearning/cnn_vs_fnn.ipynb)


## AI-powered tools

- [Developing a RAG framework for bioinformatics applications](https://github.com/marconotaro/llm-sib)


## DataViz

- [Interactive map of remote alpine spots that I visited in Switzerland](swissalps_map.ipynb)
- [Visualization of Michigan's temperature records](dataviz/weather-records.ipynb)
- [Visualization of Detroit's sports teams win percentages](dataviz/detroit-wiki.ipynb)

